#!/usr/bin/env bash
# regen-index.sh — Rebuild .claude/memory/INDEX.md and .claude/history/INDEX.md
# deterministically from the per-chat chat-*.md files.
#
# WHY: INDEX.md is a *derived* aggregate view (SSOT = each chat-*.md). It used to
# be git-tracked AND rewritten in full by the LLM on every task-tracker run, which
# made it the #1 merge-conflict source across parallel chats. It is now git-ignored
# and rebuilt locally by this script — no two chats ever commit it, so it cannot
# conflict. See CLAUDE.md §9 / docs/known-issues for the rationale.
#
# Properties: idempotent, no network, no git writes, cwd-independent. Safe to run
# from SessionStart hooks and from task-tracker. On legacy projects (no
# .claude/memory/) it exits 0 silently.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"   # .claude/hooks -> project root
MEM_DIR="$ROOT/.claude/memory"
HIST_DIR="$ROOT/.claude/history"

# Per-chat mechanism absent (legacy project) → nothing to do.
[ -d "$MEM_DIR" ] || exit 0

NOW="$(date '+%Y-%m-%d %H:%M:%S')"

# List chat-*.md in a dir (sorted, excludes INDEX.md which doesn't match chat-*).
chat_files() {
  find "$1" -maxdepth 1 -name 'chat-*.md' -type f 2>/dev/null | LC_ALL=C sort
}

# Print the body lines of a "## <section>" block (heading excluded), stopping at
# the next top-level "## " heading or EOF. Note: "### " lines are NOT treated as
# section boundaries (index of "## " in "### x" is 2, not 1).
section_body() {
  awk -v sec="$2" '
    index($0, "## ") == 1 {
      cur = substr($0, 4)
      inseg = (cur == sec) ? 1 : 0
      next
    }
    inseg { print }
  ' "$1"
}

# ---------------------------------------------------------------------------
# memory/INDEX.md
# ---------------------------------------------------------------------------
regen_memory() {
  local inprog="" done3="" planned="" f label

  while IFS= read -r f; do
    [ -n "$f" ] || continue
    label="$(basename "$f" .md)"   # e.g. chat-du-g

    # 進行中: emit one line per "### <task>" heading (+ its 現在: line if present).
    local ip
    ip="$(section_body "$f" "進行中" | awk -v lbl="$label" '
      function emit() {
        if (h == "") return
        if (cur != "") print "- [" lbl "] " h " — 現在: " cur
        else           print "- [" lbl "] " h
      }
      /^### / { emit(); h = substr($0, 5); sub(/[[:space:]]+$/, "", h); cur = ""; next }
      /^[-*][[:space:]]*現在[:：]/ {
        c = $0; sub(/^[-*][[:space:]]*現在[:：][[:space:]]*/, "", c); cur = c
      }
      END { emit() }
    ')"
    [ -n "$ip" ] && inprog+="$ip"$'\n'

    # 直近の完了: top-level "- " bullets, max 3 per chat.
    local dn
    dn="$(section_body "$f" "直近の完了" | awk -v lbl="$label" '
      /^- / && n < 3 { line = substr($0, 3); print "- [" lbl "] " line; n++ }
    ')"
    [ -n "$dn" ] && done3+="$dn"$'\n'

    # 予定: top-level "- " bullets (all).
    local pl
    pl="$(section_body "$f" "予定" | awk -v lbl="$label" '
      /^- / { line = substr($0, 3); print "- [" lbl "] " line }
    ')"
    [ -n "$pl" ] && planned+="$pl"$'\n'
  done < <(chat_files "$MEM_DIR")

  [ -n "$inprog" ]  || inprog="- （現在 進行中タスクなし）"$'\n'
  [ -n "$done3" ]   || done3="- （なし）"$'\n'
  [ -n "$planned" ] || planned="- （なし）"$'\n'

  {
    echo "# MEMORY INDEX (auto-generated by regen-index.sh — git-ignored, do not edit)"
    echo
    echo "> 各 \`chat-*.md\` の集約ビュー。**SSOT は各 \`chat-*.md\`**。本ファイルは git 非追跡の派生物で、SessionStart hook / task-tracker が \`.claude/hooks/regen-index.sh\` で再生成する。手編集しない。"
    echo
    echo "再生成: $NOW"
    echo
    echo "---"
    echo
    echo "## 進行中 (across all chats)"
    echo
    printf '%s' "$inprog"
    echo
    echo "## 直近の完了 (across all chats, 各チャット最大 3 件)"
    echo
    printf '%s' "$done3"
    echo
    echo "## 予定 (across all chats)"
    echo
    printf '%s' "$planned"
  } > "$MEM_DIR/INDEX.md.tmp"
  mv -f "$MEM_DIR/INDEX.md.tmp" "$MEM_DIR/INDEX.md"
}

# ---------------------------------------------------------------------------
# history/INDEX.md — newest 5 "### YYYY-MM-DD - title" entries across all chats
# ---------------------------------------------------------------------------
regen_history() {
  [ -d "$HIST_DIR" ] || return 0
  local rows f label
  rows=""

  while IFS= read -r f; do
    [ -n "$f" ] || continue
    label="$(basename "$f" .md)"
    local r
    r="$(awk -v lbl="$label" '
      /^### / {
        s = substr($0, 5)
        if (match(s, /^[0-9]{4}-[0-9]{2}-[0-9]{2}/)) {
          d = substr(s, RSTART, RLENGTH)
          rest = substr(s, RSTART + RLENGTH)
          sub(/^[[:space:]]*-[[:space:]]*/, "", rest)
          printf "%s\t%s\t%s\n", d, lbl, rest
        }
      }
    ' "$f")"
    [ -n "$r" ] && rows+="$r"$'\n'
  done < <(chat_files "$HIST_DIR")

  local recent
  if [ -n "$rows" ]; then
    recent="$(printf '%s' "$rows" | LC_ALL=C sort -t$'\t' -k1,1 -r \
      | head -5 \
      | awk -F'\t' '{ printf "- %s [%s] %s\n", $1, $2, $3 }')"
  else
    recent="- （履歴なし）"
  fi

  {
    echo "# HISTORY INDEX (auto-generated by regen-index.sh — git-ignored, do not edit)"
    echo
    echo "> 各 \`chat-*.md\` の集約ビュー。**SSOT は各 \`chat-*.md\`**。git 非追跡の派生物（\`.claude/hooks/regen-index.sh\` で再生成）。"
    echo
    echo "再生成: $NOW"
    echo
    echo "---"
    echo
    echo "## 直近エントリ (across all chats, 時系列降順 5 件)"
    echo
    printf '%s\n' "$recent"
    echo
    echo "古いエントリは各 \`chat-*.md\` または \`.claude/history/archive/\` 参照。"
  } > "$HIST_DIR/INDEX.md.tmp"
  mv -f "$HIST_DIR/INDEX.md.tmp" "$HIST_DIR/INDEX.md"
}

regen_memory
regen_history
exit 0
