import { randomUUID } from "node:crypto";
import { getSupabase } from "../supabase.js";
import {
  assertDateKey,
  assertTimeOfDay,
  localToday,
} from "../utils/localDate.js";
import {
  META_COLUMNS,
  insertItem,
  requireMeta,
  softDeleteItem,
  type ItemsMetaRow,
} from "../utils/items.js";
import {
  chunkIds,
  fetchAllPages,
  fetchByIdChunks,
  resolveListLimit,
} from "../utils/pagination.js";

/*
 * Routine handlers — repeating events (#1620).
 *
 * A routine is the TEMPLATE the app expands into events: one `items_meta` row
 * (role='routine') + one `routines_payload` row. Until this file the package
 * could read `events_payload.routine_item_id` (list_schedule returns it as
 * `routineId`) but had no way to create that id or to follow it anywhere.
 *
 * WHAT THIS FILE DOES NOT DO: generate occurrences. The rules for which days a
 * routine fires on (shared/src/utils/routineFrequency.ts), what a generation
 * pass creates (routineScheduleSync.ts), the conflict rules against manual
 * edits (tier-1-core §競合解決ルール) and the (routine, source_date) dedup all
 * live in the app, and they only hold as a set. A second copy here is exactly
 * the shared/mcp fork #677 is trying to retire — and the day the two disagree,
 * one routine produces different days depending on who wrote last. So
 * `create_routine` writes the template and nothing else, and says so in its
 * result; `tests/routineHandlers.test.ts` pins that no path in `src/` writes an
 * occurrence.
 *
 * The same reason keeps two tools out (decided on #1620):
 *   - no `update_routine`: changing a frequency has to sweep the future
 *     occurrences already on the calendar, which the app's
 *     `reconcileRoutineScheduleItems` does from its editor. Rewriting only the
 *     template here would leave the old days standing.
 *   - no event → routine conversion: `convertEventToRoutine` is an ordered
 *     four-step write (#407 / #1140 guards + rollback) whose order is what
 *     keeps the composite FK from wedging.
 *
 * `routine_groups` is not exposed: the "group" frequency was removed from the
 * code in #352 and survives only in the DB CHECK.
 */

/** What every result that could be mistaken for "the calendar is ready" says. */
export const GENERATION_NOTE =
  "Occurrences are generated by the Life Editor app, not by these tools: the app creates a routine's events for the days it displays (today while it is open, plus the range the Calendar shows). Until then list_schedule does not include them.";

const FREQUENCY_TYPES = ["daily", "weekdays", "interval"] as const;
type FrequencyType = (typeof FREQUENCY_TYPES)[number];

interface RoutinesPayloadRow {
  item_id: string;
  frequency_type: string;
  frequency_days: string;
  frequency_interval: number | null;
  frequency_start_date: string | null;
  start_time: string | null;
  end_time: string | null;
  is_archived: boolean;
  is_visible: boolean;
  sort_order: number;
}

const PAYLOAD_COLUMNS =
  "item_id, frequency_type, frequency_days, frequency_interval, " +
  "frequency_start_date, start_time, end_time, is_archived, is_visible, " +
  "sort_order";

interface OccurrencePayloadRow {
  item_id: string;
  start_at: string | null;
  start_time: string | null;
  end_time: string | null;
  is_all_day: boolean;
  done: boolean;
  is_dismissed: boolean;
}

/** `frequency_days` is a JSON array string; a corrupt one reads as no days. */
function parseDays(raw: string): number[] {
  try {
    const parsed: unknown = JSON.parse(raw);
    return Array.isArray(parsed)
      ? parsed.filter((n): n is number => typeof n === "number")
      : [];
  } catch {
    return [];
  }
}

/**
 * The DB row's frequency as the app reads it. The retired "group" type is
 * still legal in the DB, and shared's `normaliseFrequency` reads it as
 * weekdays with no days — a routine that never fires. Reported the same way
 * here so the two surfaces describe one routine identically.
 */
function readFrequency(payload: RoutinesPayloadRow) {
  if (payload.frequency_type === "group") {
    return { frequencyType: "weekdays", frequencyDays: [] as number[] };
  }
  return {
    frequencyType: payload.frequency_type,
    frequencyDays: parseDays(payload.frequency_days),
  };
}

function formatRoutine(meta: ItemsMetaRow, payload: RoutinesPayloadRow) {
  return {
    id: meta.id,
    title: meta.title,
    ...readFrequency(payload),
    frequencyInterval: payload.frequency_interval,
    frequencyStartDate: payload.frequency_start_date,
    startTime: payload.start_time,
    endTime: payload.end_time,
    isArchived: payload.is_archived,
    isVisible: payload.is_visible,
    createdAt: meta.created_at,
    updatedAt: meta.updated_at,
  };
}

async function fetchPayload(id: string): Promise<RoutinesPayloadRow | null> {
  const { client } = await getSupabase();
  const { data, error } = await client
    .from("routines_payload")
    .select(PAYLOAD_COLUMNS)
    .eq("item_id", id)
    .maybeSingle();
  if (error) throw new Error(`get routines_payload: ${error.message}`);
  return (data as unknown as RoutinesPayloadRow | null) ?? null;
}

/** One live routine (meta + payload) or a not-found error. */
async function getRoutineRows(id: string) {
  const meta = await requireMeta(id, "routine", "Routine");
  const payload = await fetchPayload(id);
  // A meta row without its payload is a §10.5 orphan — not a routine anyone
  // can use, so it reads as missing rather than as a half-filled result.
  if (!payload) throw new Error(`Routine not found: ${id}`);
  return { meta, payload };
}

/** Ids of the live events generated from `routineId`, paged past the cap. */
async function fetchOccurrenceIds(routineId: string): Promise<string[]> {
  const { client } = await getSupabase();
  const rows = await fetchAllPages<{ item_id: string }>(
    (from, to) =>
      client
        .from("events_payload")
        .select("item_id")
        .eq("routine_item_id", routineId)
        .eq("is_deleted_cache", false)
        .order("item_id", { ascending: true })
        .range(from, to),
    "list routine occurrences",
  );
  return rows.map((r) => r.item_id);
}

export async function listRoutines(args: {
  include_archived?: boolean;
  limit?: number;
}) {
  const limit = resolveListLimit(args.limit);
  const { client } = await getSupabase();

  const metas = await fetchAllPages<ItemsMetaRow>(
    (from, to) =>
      client
        .from("items_meta")
        .select(META_COLUMNS)
        .eq("role", "routine")
        .eq("is_deleted", false)
        .order("id", { ascending: true })
        .range(from, to),
    "list routine items_meta",
  );
  if (metas.length === 0) return { routines: [], total: 0, hasMore: false };

  const payloads = await fetchByIdChunks<RoutinesPayloadRow>(
    metas.map((m) => m.id),
    async (chunk) => {
      const { data, error } = await client
        .from("routines_payload")
        .select(PAYLOAD_COLUMNS)
        .in("item_id", chunk);
      if (error) throw new Error(`list routines_payload: ${error.message}`);
      return (data ?? []) as unknown as RoutinesPayloadRow[];
    },
  );
  const payloadById = new Map(payloads.map((p) => [p.item_id, p]));

  const joined = metas
    .flatMap((meta) => {
      const payload = payloadById.get(meta.id);
      return payload ? [{ meta, payload }] : [];
    })
    .filter(({ payload }) => args.include_archived || !payload.is_archived)
    // The app's list order: sort_order, then oldest first.
    .sort(
      (a, b) =>
        a.payload.sort_order - b.payload.sort_order ||
        a.meta.created_at.localeCompare(b.meta.created_at) ||
        a.meta.id.localeCompare(b.meta.id),
    );

  return {
    routines: joined
      .slice(0, limit)
      .map(({ meta, payload }) => formatRoutine(meta, payload)),
    total: joined.length,
    hasMore: joined.length > limit,
  };
}

/**
 * A routine and the occurrences that already exist for it — the place a
 * `routineId` from list_schedule leads. Occurrences are read, never made: a
 * day the app has not displayed yet is simply absent (see GENERATION_NOTE).
 */
export async function getRoutine(args: {
  id: string;
  start_date?: string;
  end_date?: string;
  limit?: number;
}) {
  if (Boolean(args.start_date) !== Boolean(args.end_date)) {
    const given = args.start_date ? "start_date" : "end_date";
    const missing = args.start_date ? "end_date" : "start_date";
    throw new Error(`${missing} is required when ${given} is given`);
  }
  if (args.start_date && args.end_date) {
    assertDateKey(args.start_date);
    assertDateKey(args.end_date);
    if (args.start_date > args.end_date) {
      throw new Error(
        `start_date ${args.start_date} is after end_date ${args.end_date}`,
      );
    }
  }
  const limit = resolveListLimit(args.limit);

  const { meta, payload } = await getRoutineRows(args.id);
  const { client } = await getSupabase();

  const occurrencePayloads = await fetchAllPages<OccurrencePayloadRow>(
    (from, to) => {
      let q = client
        .from("events_payload")
        .select(
          "item_id, start_at, start_time, end_time, is_all_day, done, is_dismissed",
        )
        .eq("routine_item_id", args.id)
        .eq("is_deleted_cache", false);
      if (args.start_date && args.end_date) {
        q = q.gte("start_at", args.start_date).lte("start_at", args.end_date);
      }
      return q
        .order("start_at", { ascending: true })
        .order("item_id", { ascending: true })
        .range(from, to);
    },
    "list routine occurrences",
  );

  const liveMetas = await fetchByIdChunks<{ id: string; title: string }>(
    occurrencePayloads.map((p) => p.item_id),
    async (chunk) => {
      const { data, error } = await client
        .from("items_meta")
        .select("id, title")
        .eq("role", "event")
        .eq("is_deleted", false)
        .in("id", chunk);
      if (error)
        throw new Error(`list occurrence items_meta: ${error.message}`);
      return (data ?? []) as { id: string; title: string }[];
    },
  );
  const titleById = new Map(liveMetas.map((m) => [m.id, m.title]));

  const occurrences = occurrencePayloads
    .filter((p) => titleById.has(p.item_id))
    .map((p) => ({
      id: p.item_id,
      date: p.start_at,
      title: titleById.get(p.item_id) as string,
      startTime: p.start_time,
      endTime: p.end_time,
      isAllDay: p.is_all_day,
      completed: p.done,
      isDismissed: p.is_dismissed,
    }));

  return {
    routine: formatRoutine(meta, payload),
    occurrences: occurrences.slice(0, limit),
    total: occurrences.length,
    hasMore: occurrences.length > limit,
    note: GENERATION_NOTE,
  };
}

interface CreateRoutineArgs {
  title: string;
  frequency_type: FrequencyType;
  frequency_days?: number[];
  frequency_interval?: number;
  frequency_start_date?: string;
  start_time?: string;
  end_time?: string;
}

/**
 * The four frequency columns for a create call, or an error naming what is
 * missing or misplaced.
 *
 * Only the fields the chosen type reads are accepted. A `frequency_days` sent
 * with "daily" would be stored and never consulted, so the caller would
 * believe they had made a Mon/Wed/Fri routine that in fact fires every day —
 * refusing is the only honest answer. The app's editor seeds a missing
 * weekday from the day being edited; a tool call has no such day, so here a
 * weekdays routine has to name its days.
 */
function resolveFrequency(args: CreateRoutineArgs) {
  const has = (value: unknown) => value !== undefined && value !== null;
  const refuse = (field: string, type: FrequencyType) =>
    new Error(
      `${field} only applies to frequency_type "${type}" (got "${args.frequency_type}")`,
    );

  switch (args.frequency_type) {
    case "daily": {
      if (has(args.frequency_days)) throw refuse("frequency_days", "weekdays");
      if (has(args.frequency_interval))
        throw refuse("frequency_interval", "interval");
      if (has(args.frequency_start_date))
        throw refuse("frequency_start_date", "interval");
      return {
        frequency_type: "daily" as const,
        frequency_days: [] as number[],
        frequency_interval: null,
        frequency_start_date: null,
      };
    }

    case "weekdays": {
      if (has(args.frequency_interval))
        throw refuse("frequency_interval", "interval");
      if (has(args.frequency_start_date))
        throw refuse("frequency_start_date", "interval");
      const days = args.frequency_days ?? [];
      if (days.length === 0) {
        throw new Error(
          'frequency_days is required for frequency_type "weekdays" (0=Sun … 6=Sat)',
        );
      }
      for (const day of days) {
        if (!Number.isInteger(day) || day < 0 || day > 6) {
          throw new Error(
            `frequency_days must hold integers 0-6 (0=Sun … 6=Sat), got ${day}`,
          );
        }
      }
      return {
        frequency_type: "weekdays" as const,
        frequency_days: [...new Set(days)].sort((a, b) => a - b),
        frequency_interval: null,
        frequency_start_date: null,
      };
    }

    case "interval": {
      if (has(args.frequency_days)) throw refuse("frequency_days", "weekdays");
      const interval = args.frequency_interval;
      if (interval === undefined || interval === null) {
        throw new Error(
          'frequency_interval is required for frequency_type "interval"',
        );
      }
      if (!Number.isInteger(interval) || interval < 1) {
        throw new Error(
          `frequency_interval must be a positive integer (got ${interval})`,
        );
      }
      // The app anchors an unset start on the day being edited; for a tool
      // call that day is today. Stored explicitly — a null start reads as
      // "fires never" in the app (#407).
      const start = args.frequency_start_date ?? localToday();
      assertDateKey(start);
      return {
        frequency_type: "interval" as const,
        frequency_days: [] as number[],
        frequency_interval: interval,
        frequency_start_date: start,
      };
    }

    default:
      throw new Error(
        `frequency_type must be one of ${FREQUENCY_TYPES.join(" | ")} (got ${JSON.stringify(args.frequency_type)})`,
      );
  }
}

export async function createRoutine(args: CreateRoutineArgs) {
  const frequency = resolveFrequency(args);

  // Both or neither: a routine with one time is a shape the app's editor
  // never produces. Neither = the app's generation default (09:00-09:30).
  if (Boolean(args.start_time) !== Boolean(args.end_time)) {
    throw new Error(
      "start_time and end_time go together (pass both, or neither for the app's default slot)",
    );
  }
  if (args.start_time) assertTimeOfDay(args.start_time, "start_time");
  if (args.end_time) assertTimeOfDay(args.end_time, "end_time");

  // generateId("routine") in shared — the id is a String with the role prefix.
  const id = `routine-${randomUUID()}`;

  // Column for column what shared's `routineNodeToRows` writes for a new
  // routine, so the app reads a tool-made routine exactly like its own.
  await insertItem({
    id,
    role: "routine",
    title: args.title,
    payloadTable: "routines_payload",
    payload: {
      // parent-plan (DU-A) columns: always null until that contract lands
      frequency: null,
      interval: null,
      weekdays_json: null,
      start_at: null,
      end_at: null,
      template_start_time: null,
      template_end_time: null,
      template_memo: null,
      template_reminder_offset_min: null,
      // current-shape columns
      is_archived: false,
      frequency_type: frequency.frequency_type,
      frequency_days: JSON.stringify(frequency.frequency_days),
      frequency_interval: frequency.frequency_interval,
      frequency_start_date: frequency.frequency_start_date,
      is_visible: true,
      start_time: args.start_time ?? null,
      end_time: args.end_time ?? null,
      reminder_enabled: false,
      reminder_offset: null,
      sort_order: 0,
    },
  });

  const { meta, payload } = await getRoutineRows(id);
  return { ...formatRoutine(meta, payload), note: GENERATION_NOTE };
}

/**
 * Trash a routine and every live occurrence it generated — the app's "delete
 * all events" (`softDeleteRoutine`), in the same order: find the occurrences,
 * trash the routine, trash the occurrences. Leaving the occurrences live would
 * strand calendar events pointing at a trashed routine.
 */
export async function deleteRoutine(args: { id: string }) {
  await requireMeta(args.id, "routine", "Routine");

  const occurrenceIds = await fetchOccurrenceIds(args.id);
  await softDeleteItem(args.id, "routine");

  if (occurrenceIds.length > 0) {
    const { client } = await getSupabase();
    const now = new Date().toISOString();
    for (const chunk of chunkIds(occurrenceIds)) {
      const { error } = await client
        .from("items_meta")
        .update({ is_deleted: true, deleted_at: now, updated_at: now })
        .in("id", chunk)
        .eq("role", "event");
      if (error)
        throw new Error(`delete routine occurrences: ${error.message}`);
    }
  }

  return {
    success: true,
    id: args.id,
    softDeleted: true,
    trashedOccurrenceIds: occurrenceIds,
  };
}
