import { describe, it, expect, vi } from "vitest";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, relative, resolve, sep } from "node:path";
import {
  createSupabaseStub,
  fromTables,
  inFilter,
  type QueryCall,
  type StubTables,
  type SupabaseStub,
} from "./supabaseStub.js";

let stub: SupabaseStub = createSupabaseStub();
vi.mock("../src/supabase.js", () => ({
  getSupabase: async () => stub,
}));

// Dynamic on purpose: a static import would be hoisted above vi.mock and read
// the real supabase module before the stub exists.
const { createRoutine, listRoutines, getRoutine, deleteRoutine } =
  await import("../src/handlers/routineHandlers.js");
const { localToday } = await import("../src/utils/localDate.js");
const { rejection } = await import("./rejection.js");

/*
 * Routine tools (#1620).
 *
 * The decision these tests exist to hold: occurrence generation stays in the
 * app. The rules for which days a routine fires on live in
 * shared/src/utils/routineFrequency.ts and routineScheduleSync.ts, and a copy
 * here would fork them the way #677 describes. So the create path must write
 * the template and nothing else, and no file in src/ may mint an occurrence —
 * pinned below both by the writes a call makes and by a scan of the source.
 */

const META = {
  title: "gym",
  is_deleted: false,
  deleted_at: null,
  created_at: "2026-09-01T00:00:00Z",
  updated_at: "2026-09-01T00:00:00Z",
};

const PAYLOAD = {
  frequency_type: "weekdays",
  frequency_days: "[2]",
  frequency_interval: null,
  frequency_start_date: null,
  start_time: "19:00",
  end_time: "20:00",
  is_archived: false,
  is_visible: true,
  sort_order: 0,
};

/** Answers the create path's read-back for whatever id it just minted. */
const readBack = (call: QueryCall) =>
  call.table === "items_meta"
    ? { ...META, id: call.filters.id, role: "routine" }
    : { ...PAYLOAD, item_id: call.filters.item_id };

const writesTo = (table: string) =>
  stub.writes().filter((c) => c.table === table);

describe("createRoutine", () => {
  it("writes the template rows and not a single occurrence", async () => {
    stub = createSupabaseStub(readBack);

    const result = await createRoutine({
      title: "gym",
      frequency_type: "weekdays",
      frequency_days: [2],
      start_time: "19:00",
      end_time: "20:00",
    });

    expect(stub.writes().map((c) => `${c.op} ${c.table}`)).toEqual([
      "insert items_meta",
      "insert routines_payload",
    ]);
    const [meta] = writesTo("items_meta");
    expect(meta.values).toMatchObject({ role: "routine", title: "gym" });
    expect(String(meta.values?.id)).toMatch(/^routine-/);

    expect(writesTo("routines_payload")[0].values).toMatchObject({
      item_id: meta.values?.id,
      frequency_type: "weekdays",
      frequency_days: "[2]",
      frequency_interval: null,
      frequency_start_date: null,
      start_time: "19:00",
      end_time: "20:00",
      is_archived: false,
      is_visible: true,
      reminder_enabled: false,
      sort_order: 0,
    });

    expect(result).toMatchObject({
      id: meta.values?.id,
      frequencyType: "weekdays",
      frequencyDays: [2],
    });
    // The caller is told the calendar is not filled in yet.
    expect(result.note).toMatch(/generated by the Life Editor app/);
  });

  it.each([
    { title: "t", frequency_type: "daily" as const },
    {
      title: "t",
      frequency_type: "weekdays" as const,
      frequency_days: [1, 3, 5],
    },
    {
      title: "t",
      frequency_type: "interval" as const,
      frequency_interval: 2,
      frequency_start_date: "2026-09-14",
    },
  ])("never writes events_payload for $frequency_type", async (args) => {
    stub = createSupabaseStub(readBack);

    await createRoutine(args);

    expect(writesTo("events_payload")).toEqual([]);
  });

  it("stores weekdays sorted and without repeats", async () => {
    stub = createSupabaseStub(readBack);

    await createRoutine({
      title: "t",
      frequency_type: "weekdays",
      frequency_days: [5, 1, 5, 3],
    });

    expect(writesTo("routines_payload")[0].values?.frequency_days).toBe(
      "[1,3,5]",
    );
  });

  it("anchors an interval routine on today when no start date is given", async () => {
    stub = createSupabaseStub(readBack);

    await createRoutine({
      title: "t",
      frequency_type: "interval",
      frequency_interval: 3,
    });

    // A null start reads as "fires never" in the app (#407).
    expect(writesTo("routines_payload")[0].values).toMatchObject({
      frequency_interval: 3,
      frequency_start_date: localToday(),
    });
  });

  it("stores no times when neither is given (the app's default slot)", async () => {
    stub = createSupabaseStub(readBack);

    await createRoutine({ title: "t", frequency_type: "daily" });

    expect(writesTo("routines_payload")[0].values).toMatchObject({
      start_time: null,
      end_time: null,
    });
  });

  it.each([
    [
      "weekdays without days",
      { frequency_type: "weekdays", frequency_days: [] },
      /frequency_days is required/,
    ],
    [
      "a weekday outside 0-6",
      { frequency_type: "weekdays", frequency_days: [7] },
      /integers 0-6/,
    ],
    [
      "a fractional weekday",
      { frequency_type: "weekdays", frequency_days: [1.5] },
      /integers 0-6/,
    ],
    [
      "interval without a count",
      { frequency_type: "interval" },
      /frequency_interval is required/,
    ],
    [
      "a zero interval",
      { frequency_type: "interval", frequency_interval: 0 },
      /positive integer/,
    ],
    [
      "a malformed start date",
      {
        frequency_type: "interval",
        frequency_interval: 2,
        frequency_start_date: "9/14",
      },
      /Invalid date/,
    ],
    [
      "days on a daily routine",
      { frequency_type: "daily", frequency_days: [1] },
      /frequency_days only applies to frequency_type "weekdays"/,
    ],
    [
      "an interval on a weekdays routine",
      {
        frequency_type: "weekdays",
        frequency_days: [1],
        frequency_interval: 2,
      },
      /frequency_interval only applies/,
    ],
    [
      "a start date on a daily routine",
      { frequency_type: "daily", frequency_start_date: "2026-09-14" },
      /frequency_start_date only applies/,
    ],
    [
      "the retired group type",
      { frequency_type: "group" },
      /frequency_type must be one of/,
    ],
    [
      "a start time alone",
      { frequency_type: "daily", start_time: "09:00" },
      /go together/,
    ],
    [
      "a malformed time",
      { frequency_type: "daily", start_time: "9:00", end_time: "10:00" },
      /Invalid start_time/,
    ],
  ])("refuses %s before writing anything", async (_label, extra, message) => {
    stub = createSupabaseStub(readBack);

    const error = await rejection(
      // Deliberately outside the argument type: these are the calls the
      // schema validator would let through or a direct caller could make.
      createRoutine({ title: "t", ...extra } as unknown as Parameters<
        typeof createRoutine
      >[0]),
    );

    expect(error.message).toMatch(message);
    expect(stub.writes()).toEqual([]);
  });
});

const routineMeta = (id: string, over: Record<string, unknown> = {}) => ({
  ...META,
  id,
  role: "routine",
  title: id,
  ...over,
});

const routinePayload = (id: string, over: Record<string, unknown> = {}) => ({
  ...PAYLOAD,
  item_id: id,
  ...over,
});

describe("listRoutines", () => {
  const tables = (): StubTables => ({
    items_meta: [
      routineMeta("routine-b", { created_at: "2026-09-02T00:00:00Z" }),
      routineMeta("routine-a"),
      routineMeta("routine-archived"),
      routineMeta("routine-trashed", { is_deleted: true }),
      routineMeta("routine-orphan"),
      { ...META, id: "si-1", role: "event" },
    ],
    routines_payload: [
      routinePayload("routine-b"),
      routinePayload("routine-a"),
      routinePayload("routine-archived", { is_archived: true }),
      routinePayload("routine-trashed"),
      // no payload for routine-orphan (a §10.5 orphan)
    ],
  });

  it("lists live routines in the app's order, skipping archived and orphaned ones", async () => {
    stub = createSupabaseStub(fromTables(tables()));

    const result = await listRoutines({});

    expect(result.routines.map((r) => r.id)).toEqual([
      "routine-a",
      "routine-b",
    ]);
    expect(result).toMatchObject({ total: 2, hasMore: false });
    expect(stub.writes()).toEqual([]);
  });

  it("includes archived routines on request", async () => {
    stub = createSupabaseStub(fromTables(tables()));

    const result = await listRoutines({ include_archived: true });

    expect(result.routines.map((r) => r.id)).toContain("routine-archived");
  });

  it("caps the page and says there is more", async () => {
    stub = createSupabaseStub(fromTables(tables()));

    const result = await listRoutines({ limit: 1 });

    expect(result.routines).toHaveLength(1);
    expect(result).toMatchObject({ total: 2, hasMore: true });
  });

  it("reads a legacy group routine the way the app does: weekdays, no days", async () => {
    stub = createSupabaseStub(
      fromTables({
        items_meta: [routineMeta("routine-g")],
        routines_payload: [
          routinePayload("routine-g", {
            frequency_type: "group",
            frequency_days: "[1,2]",
          }),
        ],
      }),
    );

    const [routine] = (await listRoutines({})).routines;

    expect(routine).toMatchObject({
      frequencyType: "weekdays",
      frequencyDays: [],
    });
  });
});

const occurrence = (
  id: string,
  date: string,
  over: Record<string, unknown> = {},
) => ({
  item_id: id,
  start_at: date,
  start_time: "19:00",
  end_time: "20:00",
  is_all_day: false,
  done: false,
  is_dismissed: false,
  routine_item_id: "routine-1",
  is_deleted_cache: false,
  ...over,
});

const eventMeta = (id: string, over: Record<string, unknown> = {}) => ({
  ...META,
  id,
  role: "event",
  ...over,
});

describe("getRoutine", () => {
  const tables = (): StubTables => ({
    items_meta: [
      routineMeta("routine-1"),
      eventMeta("si-3"),
      eventMeta("si-1"),
      eventMeta("si-2", { title: "gym (moved)" }),
      eventMeta("si-trashed", { is_deleted: true }),
      eventMeta("si-other"),
    ],
    routines_payload: [routinePayload("routine-1")],
    events_payload: [
      occurrence("si-3", "2026-09-22"),
      occurrence("si-1", "2026-09-08", { done: true }),
      occurrence("si-2", "2026-09-15", { is_dismissed: true }),
      occurrence("si-trashed", "2026-09-29", { is_deleted_cache: true }),
      occurrence("si-other", "2026-09-10", { routine_item_id: "routine-2" }),
    ],
  });

  it("leads from a routineId to the series and its existing occurrences", async () => {
    stub = createSupabaseStub(fromTables(tables()));

    const result = await getRoutine({ id: "routine-1" });

    expect(result.routine).toMatchObject({
      id: "routine-1",
      frequencyType: "weekdays",
      frequencyDays: [2],
    });
    expect(result.occurrences).toEqual([
      expect.objectContaining({
        id: "si-1",
        date: "2026-09-08",
        completed: true,
      }),
      expect.objectContaining({
        id: "si-2",
        title: "gym (moved)",
        isDismissed: true,
      }),
      expect.objectContaining({ id: "si-3", date: "2026-09-22" }),
    ]);
    expect(result).toMatchObject({ total: 3, hasMore: false });
    expect(result.note).toMatch(/generated by the Life Editor app/);
    expect(stub.writes()).toEqual([]);
  });

  it("narrows occurrences to a date range", async () => {
    stub = createSupabaseStub(fromTables(tables()));

    const result = await getRoutine({
      id: "routine-1",
      start_date: "2026-09-10",
      end_date: "2026-09-20",
    });

    expect(result.occurrences.map((o) => o.id)).toEqual(["si-2"]);
  });

  it("caps occurrences and reports the rest", async () => {
    stub = createSupabaseStub(fromTables(tables()));

    const result = await getRoutine({ id: "routine-1", limit: 2 });

    expect(result.occurrences.map((o) => o.id)).toEqual(["si-1", "si-2"]);
    expect(result).toMatchObject({ total: 3, hasMore: true });
  });

  it("refuses half a range", async () => {
    stub = createSupabaseStub(fromTables(tables()));

    await expect(
      getRoutine({ id: "routine-1", start_date: "2026-09-10" }),
    ).rejects.toThrow("end_date is required when start_date is given");
  });

  it("throws for an id that is not a live routine", async () => {
    stub = createSupabaseStub(fromTables(tables()));

    await expect(getRoutine({ id: "si-1" })).rejects.toThrow(
      "Routine not found: si-1",
    );
  });
});

describe("deleteRoutine", () => {
  const tables = (): StubTables => ({
    items_meta: [routineMeta("routine-1")],
    events_payload: [
      occurrence("si-1", "2026-09-08", { done: true }),
      occurrence("si-2", "2026-09-15"),
      occurrence("si-trashed", "2026-09-22", { is_deleted_cache: true }),
      occurrence("si-other", "2026-09-10", { routine_item_id: "routine-2" }),
    ],
  });

  it("trashes the routine, then every live occurrence it generated", async () => {
    stub = createSupabaseStub(fromTables(tables()));

    const result = await deleteRoutine({ id: "routine-1" });

    expect(result).toEqual({
      success: true,
      id: "routine-1",
      softDeleted: true,
      trashedOccurrenceIds: ["si-1", "si-2"],
    });

    const writes = stub.writes();
    expect(writes).toHaveLength(2);
    expect(writes.every((w) => w.table === "items_meta")).toBe(true);
    expect(writes.every((w) => w.op === "update")).toBe(true);

    expect(writes[0].filters).toEqual({ id: "routine-1", role: "routine" });
    expect(writes[0].values).toMatchObject({ is_deleted: true });

    expect(writes[1].filters).toEqual({ role: "event" });
    expect(inFilter(writes[1], "id")).toEqual(["si-1", "si-2"]);
    expect(writes[1].values).toMatchObject({ is_deleted: true });
    expect(writes[1].values).toHaveProperty("updated_at"); // §10.2 LWW bump
  });

  it("trashes only the routine when nothing was generated yet", async () => {
    stub = createSupabaseStub(
      fromTables({ items_meta: [routineMeta("routine-1")] }),
    );

    const result = await deleteRoutine({ id: "routine-1" });

    expect(result.trashedOccurrenceIds).toEqual([]);
    expect(stub.writes()).toHaveLength(1);
  });

  it("writes nothing for an id that is not a live routine", async () => {
    stub = createSupabaseStub(fromTables(tables()));

    await expect(deleteRoutine({ id: "routine-9" })).rejects.toThrow(
      "Routine not found: routine-9",
    );
    expect(stub.writes()).toEqual([]);
  });
});

/*
 * The source-level half of the decision. The behavioural tests above cover
 * the routine tools; this covers everything else in the package, including a
 * tool nobody has written yet. An occurrence is an events_payload row whose
 * routine_item_id is set, so the one thing no file may do is assign that
 * column anything but null. Type annotations (`routine_item_id: string |
 * null`) are the only other shape the column name takes before a colon.
 */
describe("occurrence generation is not duplicated in the MCP server", () => {
  const srcDir = resolve(dirname(fileURLToPath(import.meta.url)), "../src");

  const walk = (dir: string): string[] =>
    readdirSync(dir).flatMap((name) => {
      const path = join(dir, name);
      if (statSync(path).isDirectory()) return walk(path);
      return path.endsWith(".ts") ? [path] : [];
    });

  it("assigns routine_item_id nothing but null anywhere in src/", () => {
    const offenders: string[] = [];
    for (const file of walk(srcDir)) {
      const source = readFileSync(file, "utf8");
      for (const [, value] of source.matchAll(
        /routine_item_id\s*:\s*([^,;\n}]+)/g,
      )) {
        const assigned = value.trim();
        if (assigned === "null" || assigned.startsWith("string")) continue;
        offenders.push(
          `${relative(srcDir, file).split(sep).join("/")}: ${assigned}`,
        );
      }
    }
    expect(offenders).toEqual([]);
  });
});
