// @vitest-environment node
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { describe, it, expect } from "vitest";
import { TOOLS } from "../src/tools.js";

/*
 * The committed tool catalog against the live registry (#1210).
 *
 * Settings shows what Claude Code can do to this database, and it reads that
 * list from `shared/src/generated/mcpToolCatalog.json` — generated by
 * `npm run catalog`, because shared/ cannot import the registry without
 * pulling the Supabase-backed handlers into the browser bundle.
 *
 * Generation is a manual step, so the catalog CAN drift: add a tool, ship it,
 * and Settings keeps advertising yesterday's list. This suite is what makes
 * that impossible to miss. It compares names and descriptions rather than
 * asserting a number — a count pinned here would be a second copy of a fact
 * that already has an owner (数値の非複製原則), and it would go green for the
 * wrong reason the moment a tool was renamed rather than added.
 *
 * When this fails, the fix is not to edit the JSON: run
 *   cd mcp-server && npm run catalog
 * and commit what it writes.
 */

const here = dirname(fileURLToPath(import.meta.url));
const CATALOG_PATH = resolve(
  here,
  "../../shared/src/generated/mcpToolCatalog.json",
);

interface CatalogEntry {
  name: string;
  description: string;
  inputSchema: unknown;
}

const catalog = JSON.parse(
  readFileSync(CATALOG_PATH, "utf8"),
) as CatalogEntry[];

const REGEN = "run `cd mcp-server && npm run catalog` and commit the result";

describe("mcpToolCatalog.json", () => {
  it("advertises exactly the tools the registry publishes", () => {
    expect(catalog.map((t) => t.name), REGEN).toEqual(TOOLS.map((t) => t.name));
  });

  it("carries the registry's descriptions and schemas verbatim", () => {
    for (const tool of TOOLS) {
      const entry = catalog.find((t) => t.name === tool.name);
      expect(entry, `${tool.name} missing from the catalog — ${REGEN}`).toBeDefined();
      expect(entry?.description, `${tool.name} description — ${REGEN}`).toBe(
        tool.description,
      );
      expect(entry?.inputSchema, `${tool.name} inputSchema — ${REGEN}`).toEqual(
        tool.inputSchema,
      );
    }
  });

  it("publishes nothing the registry does not", () => {
    const known = new Set(TOOLS.map((t) => t.name));
    const extra = catalog.filter((t) => !known.has(t.name)).map((t) => t.name);
    expect(extra, `stale entries — ${REGEN}`).toEqual([]);
  });
});
