import {
  ArrowLeftRight,
  ArrowRightLeft,
  BarChart3,
  Bell,
  BookOpen,
  Calendar,
  CalendarRange,
  CheckCircle2,
  CheckSquare,
  ClipboardList,
  Clock,
  Columns2,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Flame,
  FolderOpen,
  Folders,
  Gauge,
  Hash,
  History,
  Image as ImageIcon,
  Keyboard,
  LayoutGrid,
  Layers,
  Link,
  Link2,
  List,
  ListChecks,
  ListTree,
  MapPin,
  Maximize2,
  Mic,
  MousePointerClick,
  Move,
  Music,
  Network,
  Palette,
  PanelRight,
  Pencil,
  Pin,
  Play,
  PlayCircle,
  Plus,
  Power,
  Repeat,
  Rows2,
  Save,
  Search,
  Server,
  Settings,
  Share2,
  ShieldCheck,
  SkipForward,
  Sliders,
  Sparkles,
  Split,
  Sun,
  Tag,
  Tags,
  Target,
  Terminal as TerminalIcon,
  Timer,
  Trash2,
  TrendingUp,
  Volume2,
  Workflow,
} from "lucide-react";
import type { SectionTipsMap, TipDefinition } from "../types/tips";

function tabKey(section: string, tab: string) {
  return `tips.${section}.tabs.${tab}.label`;
}
function tipKey(
  section: string,
  tab: string,
  item: string,
  kind: "title" | "description",
) {
  return `tips.${section}.tabs.${tab}.items.${item}.${kind}`;
}

function makeTip(
  section: string,
  tab: string,
  item: string,
  icon: TipDefinition["icon"],
): TipDefinition {
  return {
    id: `${section}-${tab}-${item}`,
    icon,
    titleKey: tipKey(section, tab, item, "title"),
    descriptionKey: tipKey(section, tab, item, "description"),
  };
}

export const SECTION_TIPS: SectionTipsMap = {
  schedule: [
    {
      id: "calendar",
      labelKey: tabKey("schedule", "calendar"),
      icon: Calendar,
      tips: [
        makeTip("schedule", "calendar", "viewSwitch", Calendar),
        makeTip("schedule", "calendar", "openDay", MousePointerClick),
        makeTip("schedule", "calendar", "rightSidebar", PanelRight),
        makeTip("schedule", "calendar", "folderFilter", FolderOpen),
        makeTip("schedule", "calendar", "contentFilter", Filter),
        makeTip("schedule", "calendar", "holidays", Sun),
        makeTip("schedule", "calendar", "folderColor", Palette),
        makeTip("schedule", "calendar", "addRoutineFromCell", Repeat),
        makeTip("schedule", "calendar", "switchTab", ArrowLeftRight),
      ],
    },
    {
      id: "routine",
      labelKey: tabKey("schedule", "routine"),
      icon: Repeat,
      tips: [
        makeTip("schedule", "routine", "createFromCalendar", Repeat),
        makeTip("schedule", "routine", "createFromSidebar", Plus),
        makeTip("schedule", "routine", "frequencyDaily", Calendar),
        makeTip("schedule", "routine", "frequencyWeekdays", CalendarRange),
        makeTip("schedule", "routine", "frequencyInterval", Repeat),
        makeTip("schedule", "routine", "edit", Pencil),
        makeTip("schedule", "routine", "dismiss", EyeOff),
        makeTip("schedule", "routine", "archive", ShieldCheck),
        makeTip("schedule", "routine", "delete", Trash2),
        makeTip("schedule", "routine", "tags", Tag),
      ],
    },
    {
      id: "dayflow",
      labelKey: tabKey("schedule", "dayflow"),
      icon: Workflow,
      tips: [
        makeTip("schedule", "dayflow", "openTab", Workflow),
        makeTip("schedule", "dayflow", "dragTime", Move),
        makeTip("schedule", "dayflow", "dualColumn", Columns2),
        makeTip("schedule", "dayflow", "contextAdd", MousePointerClick),
        makeTip("schedule", "dayflow", "rightClickEdit", Pencil),
        makeTip("schedule", "dayflow", "todayButton", Target),
        makeTip("schedule", "dayflow", "syncCalendar", Calendar),
        makeTip("schedule", "dayflow", "filterTypes", Filter),
        makeTip("schedule", "dayflow", "addNote", FileText),
      ],
    },
    {
      id: "stats",
      labelKey: tabKey("schedule", "stats"),
      icon: BarChart3,
      tips: [
        makeTip("schedule", "stats", "achievementPanel", PanelRight),
        makeTip("schedule", "stats", "daysCount", CheckCircle2),
        makeTip("schedule", "stats", "currentStreak", Flame),
        makeTip("schedule", "stats", "longestStreak", TrendingUp),
        makeTip("schedule", "stats", "details", Eye),
        makeTip("schedule", "stats", "perGroup", Layers),
        makeTip("schedule", "stats", "moreInAnalytics", BarChart3),
      ],
    },
  ],
  work: [
    {
      id: "taskSelect",
      labelKey: tabKey("work", "taskSelect"),
      icon: ListChecks,
      tips: [
        makeTip("work", "taskSelect", "openSelector", List),
        makeTip("work", "taskSelect", "search", Search),
        makeTip("work", "taskSelect", "folderSearch", FolderOpen),
        makeTip("work", "taskSelect", "freeSession", Sparkles),
        makeTip("work", "taskSelect", "startFromTree", PlayCircle),
        makeTip("work", "taskSelect", "switchTask", ArrowLeftRight),
        makeTip("work", "taskSelect", "completionPrompt", CheckCircle2),
      ],
    },
    {
      id: "timer",
      labelKey: tabKey("work", "timer"),
      icon: Timer,
      tips: [
        makeTip("work", "timer", "click", Play),
        makeTip("work", "timer", "spaceShortcut", Keyboard),
        makeTip("work", "timer", "resetR", History),
        makeTip("work", "timer", "modalToggle", Maximize2),
        makeTip("work", "timer", "miniWidget", Pin),
        makeTip("work", "timer", "extend", Plus),
        makeTip("work", "timer", "shorten", Timer),
        makeTip("work", "timer", "sessionComplete", SkipForward),
      ],
    },
    {
      id: "pomodoro",
      labelKey: tabKey("work", "pomodoro"),
      icon: Settings,
      tips: [
        makeTip("work", "pomodoro", "sidebarLocation", PanelRight),
        makeTip("work", "pomodoro", "durations", Clock),
        makeTip("work", "pomodoro", "longBreakRule", Repeat),
        makeTip("work", "pomodoro", "autoBreak", Sparkles),
        makeTip("work", "pomodoro", "sessionStructure", ListTree),
        makeTip("work", "pomodoro", "completionEffects", Bell),
      ],
    },
    {
      id: "audio",
      labelKey: tabKey("work", "audio"),
      icon: Music,
      tips: [
        makeTip("work", "audio", "musicTab", Music),
        makeTip("work", "audio", "playlist", PlayCircle),
        makeTip("work", "audio", "nowPlaying", PanelRight),
        makeTip("work", "audio", "customSounds", Mic),
        makeTip("work", "audio", "soundTags", Tag),
        makeTip("work", "audio", "soundFilter", Filter),
        makeTip("work", "audio", "previewVolume", Volume2),
      ],
    },
  ],
  materials: [
    {
      id: "dailyMemo",
      labelKey: tabKey("materials", "dailyMemo"),
      icon: BookOpen,
      tips: [
        makeTip("materials", "dailyMemo", "openTab", BookOpen),
        makeTip("materials", "dailyMemo", "pickDate", List),
        makeTip("materials", "dailyMemo", "searchDate", Search),
        makeTip("materials", "dailyMemo", "richEditor", FileText),
        makeTip("materials", "dailyMemo", "autoSave", Save),
        makeTip("materials", "dailyMemo", "templates", Layers),
        makeTip("materials", "dailyMemo", "linkInline", Link),
        makeTip("materials", "dailyMemo", "tagInline", Hash),
      ],
    },
    {
      id: "notes",
      labelKey: tabKey("materials", "notes"),
      icon: FileText,
      tips: [
        makeTip("materials", "notes", "create", Plus),
        makeTip("materials", "notes", "folders", FolderOpen),
        makeTip("materials", "notes", "drag", Move),
        makeTip("materials", "notes", "search", Search),
        makeTip("materials", "notes", "color", Palette),
        makeTip("materials", "notes", "iconCustom", ImageIcon),
        makeTip("materials", "notes", "softDelete", Trash2),
        makeTip("materials", "notes", "restore", History),
      ],
    },
    {
      id: "linkSyntax",
      labelKey: tabKey("materials", "linkSyntax"),
      icon: Link,
      tips: [
        makeTip("materials", "linkSyntax", "noteLink", Link),
        makeTip("materials", "linkSyntax", "tag", Hash),
        makeTip("materials", "linkSyntax", "completion", Keyboard),
        makeTip("materials", "linkSyntax", "click", MousePointerClick),
        makeTip("materials", "linkSyntax", "rename", Pencil),
        makeTip("materials", "linkSyntax", "graphLink", Network),
      ],
    },
    {
      id: "files",
      labelKey: tabKey("materials", "files"),
      icon: FolderOpen,
      tips: [
        makeTip("materials", "files", "rootFolder", FolderOpen),
        makeTip("materials", "files", "tree", Folders),
        makeTip("materials", "files", "search", Search),
        makeTip("materials", "files", "openOs", ArrowRightLeft),
        makeTip("materials", "files", "createNew", Plus),
        makeTip("materials", "files", "rename", Pencil),
        makeTip("materials", "files", "delete", Trash2),
      ],
    },
  ],
  connect: [
    {
      id: "graph",
      labelKey: tabKey("connect", "graph"),
      icon: Network,
      tips: [
        makeTip("connect", "graph", "view", Network),
        makeTip("connect", "graph", "drag", Move),
        makeTip("connect", "graph", "zoom", Maximize2),
        makeTip("connect", "graph", "focusNode", Target),
        makeTip("connect", "graph", "color", Palette),
        makeTip("connect", "graph", "savePosition", Pin),
        makeTip("connect", "graph", "fromNote", Link2),
      ],
    },
    {
      id: "tags",
      labelKey: tabKey("connect", "tags"),
      icon: Tag,
      tips: [
        makeTip("connect", "tags", "assign", Hash),
        makeTip("connect", "tags", "create", Plus),
        makeTip("connect", "tags", "rename", Pencil),
        makeTip("connect", "tags", "color", Palette),
        makeTip("connect", "tags", "filter", Filter),
        makeTip("connect", "tags", "manageInSettings", Settings),
        makeTip("connect", "tags", "graphCluster", Network),
      ],
    },
    {
      id: "backlinks",
      labelKey: tabKey("connect", "backlinks"),
      icon: Link2,
      tips: [
        makeTip("connect", "backlinks", "show", PanelRight),
        makeTip("connect", "backlinks", "unlinked", Link2),
        makeTip("connect", "backlinks", "click", MousePointerClick),
        makeTip("connect", "backlinks", "context", Eye),
        makeTip("connect", "backlinks", "count", Gauge),
        makeTip("connect", "backlinks", "navigate", ArrowRightLeft),
      ],
    },
    {
      id: "filter",
      labelKey: tabKey("connect", "filter"),
      icon: Filter,
      tips: [
        makeTip("connect", "filter", "search", Search),
        makeTip("connect", "filter", "byTag", Hash),
        makeTip("connect", "filter", "noteType", FileText),
        makeTip("connect", "filter", "memoType", BookOpen),
        makeTip("connect", "filter", "viewMode", LayoutGrid),
        makeTip("connect", "filter", "persisted", Save),
      ],
    },
  ],
  terminal: [
    {
      id: "claude",
      labelKey: tabKey("terminal", "claude"),
      icon: Sparkles,
      tips: [
        makeTip("terminal", "claude", "launchTitleBar", TerminalIcon),
        makeTip("terminal", "claude", "shortcut", Keyboard),
        makeTip("terminal", "claude", "mcpAutoConnect", Server),
        makeTip("terminal", "claude", "naturalQuery", Sparkles),
        makeTip("terminal", "claude", "exitSession", Power),
        makeTip("terminal", "claude", "switchSection", ArrowRightLeft),
        makeTip("terminal", "claude", "aiSettings", Settings),
      ],
    },
    {
      id: "shortcuts",
      labelKey: tabKey("terminal", "shortcuts"),
      icon: Keyboard,
      tips: [
        makeTip("terminal", "shortcuts", "newTab", Plus),
        makeTip("terminal", "shortcuts", "closePane", Power),
        makeTip("terminal", "shortcuts", "splitVertical", Columns2),
        makeTip("terminal", "shortcuts", "splitHorizontal", Rows2),
        makeTip("terminal", "shortcuts", "togglePanel", Keyboard),
      ],
    },
    {
      id: "panes",
      labelKey: tabKey("terminal", "panes"),
      icon: Split,
      tips: [
        makeTip("terminal", "panes", "addTab", Plus),
        makeTip("terminal", "panes", "splitV", Columns2),
        makeTip("terminal", "panes", "splitH", Rows2),
        makeTip("terminal", "panes", "maxPanes", Gauge),
        makeTip("terminal", "panes", "resizeDrag", Move),
        makeTip("terminal", "panes", "focus", MousePointerClick),
        makeTip("terminal", "panes", "closePane", Power),
        makeTip("terminal", "panes", "tabBar", LayoutGrid),
      ],
    },
    {
      id: "mcp",
      labelKey: tabKey("terminal", "mcp"),
      icon: Server,
      tips: [
        makeTip("terminal", "mcp", "registerServer", Server),
        makeTip("terminal", "mcp", "tools", ClipboardList),
        makeTip("terminal", "mcp", "createTask", CheckSquare),
        makeTip("terminal", "mcp", "queryNotes", FileText),
        makeTip("terminal", "mcp", "tagOps", Tag),
        makeTip("terminal", "mcp", "fileOps", FolderOpen),
        makeTip("terminal", "mcp", "schedule", Calendar),
        makeTip("terminal", "mcp", "claudeMd", BookOpen),
        makeTip("terminal", "mcp", "skills", MapPin),
      ],
    },
  ],
  analytics: [
    {
      id: "overview",
      labelKey: tabKey("analytics", "overview"),
      icon: LayoutGrid,
      tips: [
        makeTip("analytics", "overview", "openSection", BarChart3),
        makeTip("analytics", "overview", "todayDashboard", Gauge),
        makeTip("analytics", "overview", "periodSelector", PanelRight),
        makeTip("analytics", "overview", "datePresets", CalendarRange),
        makeTip("analytics", "overview", "weeklySummary", TrendingUp),
        makeTip("analytics", "overview", "streak", Flame),
        makeTip("analytics", "overview", "switchTabs", ArrowLeftRight),
      ],
    },
    {
      id: "tasks",
      labelKey: tabKey("analytics", "tasks"),
      icon: CheckSquare,
      tips: [
        makeTip("analytics", "tasks", "completionTrend", TrendingUp),
        makeTip("analytics", "tasks", "stagnation", History),
        makeTip("analytics", "tasks", "byProject", FolderOpen),
        makeTip("analytics", "tasks", "workTime", Clock),
        makeTip("analytics", "tasks", "filterPeriod", Filter),
        makeTip("analytics", "tasks", "tabFocus", ListChecks),
      ],
    },
    {
      id: "time",
      labelKey: tabKey("analytics", "time"),
      icon: Clock,
      tips: [
        makeTip("analytics", "time", "workChart", BarChart3),
        makeTip("analytics", "time", "heatmap", LayoutGrid),
        makeTip("analytics", "time", "balance", Sliders),
        makeTip("analytics", "time", "pomodoroRate", Target),
        makeTip("analytics", "time", "dailyTimeline", Workflow),
        makeTip("analytics", "time", "scheduleTab", Calendar),
        makeTip("analytics", "time", "eventDistribution", BarChart3),
      ],
    },
    {
      id: "knowledge",
      labelKey: tabKey("analytics", "knowledge"),
      icon: Network,
      tips: [
        makeTip("analytics", "knowledge", "noteCreation", TrendingUp),
        makeTip("analytics", "knowledge", "memoHeatmap", LayoutGrid),
        makeTip("analytics", "knowledge", "byFolder", FolderOpen),
        makeTip("analytics", "knowledge", "tagUsage", Tags),
        makeTip("analytics", "knowledge", "tagEntityType", Hash),
        makeTip("analytics", "knowledge", "connectSummary", Share2),
      ],
    },
  ],
};
