import type { ShortcutDefinition } from "../types/shortcut";

export const DEFAULT_SHORTCUTS: ShortcutDefinition[] = [
  // Global
  {
    id: "global:command-palette",
    category: "global",
    descriptionKey: "tips.shortcutsTab.openCommandPalette",
    defaultBinding: { code: "KeyK", meta: true },
    activeInInput: true,
  },
  {
    id: "global:settings",
    category: "global",
    descriptionKey: "tips.shortcutsTab.openSettings",
    defaultBinding: { code: "Comma", meta: true },
    activeInInput: true,
  },
  {
    id: "global:work-timer",
    category: "global",
    descriptionKey: "tips.shortcutsTab.toggleTimerModal",
    defaultBinding: { code: "KeyT", meta: true, shift: true },
    activeInInput: true,
  },
  {
    id: "global:play-pause",
    category: "global",
    descriptionKey: "tips.shortcutsTab.playPauseTimer",
    defaultBinding: { key: " " },
    activeInInput: false,
  },
  {
    id: "global:new-task",
    category: "global",
    descriptionKey: "tips.shortcutsTab.createNewTask",
    defaultBinding: { key: "n" },
    activeInInput: false,
  },
  {
    id: "global:reset-timer",
    category: "global",
    descriptionKey: "tips.shortcutsTab.resetTimer",
    defaultBinding: { key: "r" },
    activeInInput: false,
  },
  // Navigation
  {
    id: "nav:tasks",
    category: "navigation",
    descriptionKey: "tips.shortcutsTab.goToTasks",
    defaultBinding: { key: "1", meta: true },
    activeInInput: true,
  },
  {
    id: "nav:memo",
    category: "navigation",
    descriptionKey: "tips.shortcutsTab.goToMemo",
    defaultBinding: { key: "2", meta: true },
    activeInInput: true,
  },
  {
    id: "nav:work",
    category: "navigation",
    descriptionKey: "tips.shortcutsTab.goToWork",
    defaultBinding: { key: "3", meta: true },
    activeInInput: true,
  },
  {
    id: "nav:analytics",
    category: "navigation",
    descriptionKey: "tips.shortcutsTab.goToAnalytics",
    defaultBinding: { key: "4", meta: true },
    activeInInput: true,
  },
  // View
  {
    id: "view:toggle-sidebar",
    category: "view",
    descriptionKey: "tips.shortcutsTab.toggleLeftSidebar",
    defaultBinding: { code: "Period", meta: true },
    activeInInput: true,
  },
  {
    id: "view:toggle-terminal",
    category: "view",
    descriptionKey: "tips.shortcutsTab.toggleTerminal",
    defaultBinding: { code: "KeyJ", meta: true },
    activeInInput: true,
  },
  {
    id: "view:toggle-right-sidebar",
    category: "view",
    descriptionKey: "tips.shortcutsTab.toggleRightSidebar",
    defaultBinding: { code: "Period", meta: true, shift: true },
    activeInInput: true,
  },
  // Terminal
  {
    id: "terminal:new-tab",
    category: "terminal",
    descriptionKey: "tips.shortcutsTab.terminalNewTab",
    defaultBinding: { code: "KeyT", meta: true },
    activeInInput: true,
  },
  {
    id: "terminal:close-pane",
    category: "terminal",
    descriptionKey: "tips.shortcutsTab.terminalClosePane",
    defaultBinding: { code: "KeyW", meta: true },
    activeInInput: true,
  },
  {
    id: "terminal:split-vertical",
    category: "terminal",
    descriptionKey: "tips.shortcutsTab.terminalSplitVertical",
    defaultBinding: { code: "KeyD", meta: true },
    activeInInput: true,
  },
  {
    id: "terminal:split-horizontal",
    category: "terminal",
    descriptionKey: "tips.shortcutsTab.terminalSplitHorizontal",
    defaultBinding: { code: "KeyD", meta: true, shift: true },
    activeInInput: true,
  },
  // Task Tree
  {
    id: "tree:move-up",
    category: "taskTree",
    descriptionKey: "tips.shortcutsTab.moveBetweenTasks",
    defaultBinding: { key: "ArrowUp" },
    activeInInput: false,
  },
  {
    id: "tree:move-down",
    category: "taskTree",
    descriptionKey: "tips.shortcutsTab.moveBetweenTasks",
    defaultBinding: { key: "ArrowDown" },
    activeInInput: false,
  },
  {
    id: "tree:expand",
    category: "taskTree",
    descriptionKey: "tips.shortcutsTab.expandFolder",
    defaultBinding: { key: "ArrowRight" },
    activeInInput: false,
  },
  {
    id: "tree:collapse",
    category: "taskTree",
    descriptionKey: "tips.shortcutsTab.collapseFolder",
    defaultBinding: { key: "ArrowLeft" },
    activeInInput: false,
  },
  {
    id: "tree:toggle-complete",
    category: "taskTree",
    descriptionKey: "tips.shortcutsTab.toggleTaskCompletion",
    defaultBinding: { key: "Enter", meta: true },
    activeInInput: false,
  },
  {
    id: "tree:indent",
    category: "taskTree",
    descriptionKey: "tips.shortcutsTab.indent",
    defaultBinding: { key: "Tab" },
    activeInInput: false,
  },
  {
    id: "tree:outdent",
    category: "taskTree",
    descriptionKey: "tips.shortcutsTab.outdent",
    defaultBinding: { key: "Tab", shift: true },
    activeInInput: false,
  },
  // Edit
  {
    id: "edit:undo",
    category: "edit",
    descriptionKey: "tips.shortcutsTab.undoTaskTree",
    defaultBinding: { code: "KeyZ", meta: true },
    activeInInput: false,
  },
  {
    id: "edit:redo",
    category: "edit",
    descriptionKey: "tips.shortcutsTab.redoTaskTree",
    defaultBinding: { code: "KeyZ", meta: true, shift: true },
    activeInInput: false,
  },
  // Calendar
  {
    id: "cal:next",
    category: "calendar",
    descriptionKey: "tips.shortcutsTab.nextMonthWeek",
    defaultBinding: { key: "j" },
    activeInInput: false,
  },
  {
    id: "cal:prev",
    category: "calendar",
    descriptionKey: "tips.shortcutsTab.prevMonthWeek",
    defaultBinding: { key: "k" },
    activeInInput: false,
  },
  {
    id: "cal:today",
    category: "calendar",
    descriptionKey: "tips.shortcutsTab.jumpToToday",
    defaultBinding: { key: "t" },
    activeInInput: false,
  },
  {
    id: "cal:toggle-view",
    category: "calendar",
    descriptionKey: "tips.shortcutsTab.toggleMonthWeek",
    defaultBinding: { key: "m" },
    activeInInput: false,
  },
];
