export const STORAGE_KEYS = {
  THEME: "life-editor-theme",
  FONT_SIZE: "life-editor-font-size",
  NOTIFICATIONS_ENABLED: "life-editor-notifications-enabled",
  LEFT_SIDEBAR_OPEN: "life-editor-left-sidebar-open",
  LEFT_SIDEBAR_WIDTH: "life-editor-left-sidebar-width",
  LANGUAGE: "life-editor-language",
  MEMO_TAB: "life-editor-memo-tab",
  EFFECT_VOLUME: "life-editor-effect-volume",
  ACTIVE_CALENDAR_ID: "life-editor-active-calendar-id",
  TASK_TREE_FOLDER_FILTER: "life-editor-task-tree-folder-filter",
  TASK_TREE_SORT_MODE: "life-editor-task-tree-sort-mode",
  CALENDAR_MODE: "life-editor-calendar-mode",
  TIMER_PLAYLIST_ID: "life-editor-timer-playlist-id",
  ACTIVE_PLAYLIST_ID: "life-editor-active-playlist-id",
  ROUTINE_TIME_SLOTS: "life-editor-routine-time-slots",
  FOLDER_MOVE_CONFIRM_SKIP: "life-editor-folder-move-confirm-skip",
  TERMINAL_OPEN: "life-editor-terminal-open",
  TERMINAL_HEIGHT: "life-editor-terminal-height",
  SHORTCUT_CONFIG: "life-editor-shortcut-config",
  RIGHT_SIDEBAR_OPEN: "life-editor-right-sidebar-open",
  RIGHT_SIDEBAR_WIDTH: "life-editor-right-sidebar-width",
  TERMINAL_DOCK: "life-editor-terminal-dock",
  TERMINAL_WIDTH: "life-editor-terminal-width",
  RIGHT_SUB_TAB: "life-editor-right-sub-tab",
  MEMO_TREE_EXPANDED: "life-editor-memo-tree-expanded",
  HEADING_FONT_SIZES: "life-editor-heading-font-sizes",
} as const;
